### ISSUE TITLE
Microsoft To Do API Missing?

### ISSUE THREAD

**Issue by mihaibirsan** [microsoftgraph/msgraph-sdk-python#195]
See: https://learn.microsoft.com/en-us/graph/api/resources/todo-overview?view=graph-rest-1.0

Also, how come this library generates a snapshot of the API rather than providing a simple `client.get('/me/todo/lists')` interface? Is there any published design philosophy for this SDK?

**Comment by samwelkanda** [comment]
Hi @mihaibirsan 

This SDK covers the entire surface area of the v.1.0 Microsoft Graph API, including the ToDo endpoint. Here's an example to get a users todo lists using the SDK
```py
async def get_user_todo_lists():
    try:
        lists = await client.users.by_user_id('USER_ID').todo.lists.get()
        for list in lists.value:
            print(list.id, list.display_name)
    except APIError as e:
        print(e.response_status_code)
asyncio.run(get_user_todo_lists())
```
We decided to implement the SDK  as a full client complete with model classes and request builders instead of a simple client where you issue string requests and get back json. The advantage is that you can easily construct requests and and get back responses that have been deserialized into Python objects. You can find the SDK design [https://github.com/microsoftgraph/msgraph-sdk-design](https://github.com/microsoftgraph/msgraph-sdk-design)

However, we are open to feedback, so feel free to share what challenge you are having with using the SDK in it's current format. 
Thanks.

**Comment by samwelkanda** [comment]
Closing this for now. Feel free to re-open if you have further questions.

**Comment by mihaibirsan** [comment]
Thank you for the response! I have since switched to using the TypeScript library instead, and have limited bandwidth for testing the Python example you have shared at the moment.

Thank you for sharing the example as well as the SDK design!
