### ISSUE TITLE
Cannot even work for the README code

### ISSUE THREAD

**Issue by ThomasUN000000000** [microsoftgraph/msgraph-sdk-python#246]
Hi team, I just copy and paste the demo code from README,
and it said this one
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/137273222/a54d109b-be03-4c20-8bdd-40b5648c073d)
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/137273222/f49a5a2d-d009-4111-8e8f-4655ea56419a)
It is the same as from the README, so frustrated, could anyone offer me some help? really appreciate it

**Comment by tikicoder** [comment]
Just as a way to get around this, you can change your code slightly
This should at least get you connected.

from azure.identity.aio import ClientSecretCredential
from msgraph import GraphServiceClient, GraphRequestAdapter
from kiota_authentication_azure.azure_identity_authentication_provider import AzureIdentityAuthenticationProvider
import asyncio

auth_provider = AzureIdentityAuthenticationProvider(
credentials= ClientSecretCredential(...)), 
scopes=['https://graph.microsoft.com/.default'])
adapter = GraphRequestAdapter(auth_provider= auth_provider)
graph_client = GraphServiceClient(request_adapter= adapter)

async def get_user():
    user = await client.users.by_user_id('userPrincipalName').get()
    if user:
      print(user.display_name)

asyncio.run(get_user())

**Comment by tikicoder** [comment]
The issue i am having now is the deserialize stuff is not properly working. So the call works but no data can be displayed

The issue looks to be around maybe and update in the send_async which is part of the kiota modules. The issue is when the method _assign_field_values is called the _json_node is a string and it is expecting a dict. So the issue is either the json is not converting like it should or its expected to be a dictionary already

https://github.com/microsoft/kiota-serialization-json-python/blob/c3a107ff2931793318a88bfa5fded0ded9a69485/kiota_serialization_json/json_parse_node.py#L199

**Comment by ecerulm** [comment]
Just to improve the searchability of this issue , the core from current README.md is 
```py
# Example using async credentials and application access.
from azure.identity.aio import ClientSecretCredential
from msgraph import GraphServiceClient

credential = ClientSecretCredential(
    tenant_id='TENANT_ID',
    client_id='CLIENT_ID',
    client_secret='CLIENT_SECRET',
)
scopes = ['https://graph.microsoft.com/.default']
client = GraphServiceClient(credentials=credential, scopes=scopes)
```

and the error that it gives is 
```
TypeError: __init__() got an unexpected keyword argument 'credentials'
```

Looking at the current source code [graph_service_client.py](https://github.com/microsoftgraph/msgraph-sdk-python/blob/2ac7d3b7415994d44ae567216fb12310a92cd92d/msgraph/graph_service_client.py#LL23C13-L23C13) seems that `credentials=` is correct. So I guess the currently published version in PyPI is old 

```
msgraph-core==1.0.0a4
msgraph-sdk==1.0.0a12 
```

If you install the latest from git : 

```
python -m pip install 'msgraph-sdk @ git+https://github.com/microsoftgraph/msgraph-sdk-python@2ac7d3b7415994d44ae567216fb12310a92cd92d'
python -m pip freeze | grep msgraph
msgraph-core==1.0.0a4
msgraph-sdk @ git+https://github.com/microsoftgraph/msgraph-sdk-python@2ac7d3b7415994d44ae567216fb12310a92cd92d
```

I tried and this works (I no longer get `unexpected keyword argument`), obviously this is temporary solution until they release `1.0.0a13`

**Comment by ThomasUN000000000** [comment]
> Just as a way to get around this, you can change your code slightly This should at least get you connected.
> 
> from azure.identity.aio import ClientSecretCredential from msgraph import GraphServiceClient, GraphRequestAdapter from kiota_authentication_azure.azure_identity_authentication_provider import AzureIdentityAuthenticationProvider import asyncio
> 
> auth_provider = AzureIdentityAuthenticationProvider( credentials= ClientSecretCredential(...)), scopes=['https://graph.microsoft.com/.default']) adapter = GraphRequestAdapter(auth_provider= auth_provider) graph_client = GraphServiceClient(request_adapter= adapter)
> 
> async def get_user(): user = await client.users.by_user_id('userPrincipalName').get() if user: print(user.display_name)
> 
> asyncio.run(get_user())

Thanks for your help, mate, my problem is gone, however I'm not sure what I am assuming is correct or not, I run this python program against Azure China service, so it popped up with a new error, I assume I need to set up the environment to Azure China, I have no clue of how to do it, do you have any idea of how to adjust the code? many thx
<img width="1500" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-python/assets/137273222/03256e6d-ecc9-4ce3-ba1a-f80eff4dfb73">

**Comment by tikicoder** [comment]
@ThomasUN000000000 So that is a valid error, but really shouldn't matter for this situation as you are wanting to interact with the MS Graph which doesn't have to be Azure. The problem is it's using the Azure SDK Credentials. 
https://learn.microsoft.com/en-us/answers/questions/630113/the-following-tenants-dont-contain-accessible-subs

So if this was an azure cli command you could just pass in --allow-no-subscriptions on the login and be ok. Not sure how to get around this one either. If you used the AzureCliCredential you might be able to pre login using azure cli to get around the issue.

There are some maybe potential work around. But its a bit of a rabbit hole and anything I suggest is untested. I would rather give an MS rep a chance o reply.

**Comment by ThomasUN000000000** [comment]
@tikicoder Could I do the subscriptions via Azure portal, seems no subscription in this page...
<img width="1168" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-python/assets/137273222/aa0ae687-5642-459d-9685-0a2a502be2c9">

**Comment by tikicoder** [comment]
@ThomasUN000000000 no this is something just about how they are authenticating and then looking to set a default subscription. If I had to guess.

**Comment by tikicoder** [comment]
@ThomasUN000000000 no this is something just about how they are authenticating and then looking to set a default subscription. If I had to guess.

**Comment by tikicoder** [comment]
previous ticket with similar issue 
https://github.com/microsoftgraph/msgraph-sdk-python/issues/228

**Comment by ThomasUN000000000** [comment]
> @tikicoder Could I do the subscriptions via Azure portal, seems no subscription in this page... <img alt="image" width="1168" src="https://user-images.githubusercontent.com/137273222/247987297-aa0ae687-5642-459d-9685-0a2a502be2c9.png">

@tikicoder I mean it seems like there is no subscription links as far as I can see from the screenshot, I could only setup via CLI?

**Comment by tikicoder** [comment]
@ThomasUN000000000 the subscription links wouldn't be here.
It would be under the normal azure subscriptions. This is Azure AD. So it is probably a glitch with the credentials class since those classes are the ones from the azure sdk. Normally they wouldn't interact with a tenant unless it has subscriptions.

**Comment by ThomasUN000000000** [comment]
@tikicoder Actually I got the token from another git repo: [https://github.com/Azure-Samples/ms-identity-python-daemon/tree/master/1-Call-MsGraph-WithSecret](ms-identity-python-daemon), with the first example, and here is the screentshot of the parameters and graph api request:
<img width="1019" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-python/assets/137273222/cc45b446-3378-4863-870b-7a3a37c71f5c">
<img width="680" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-python/assets/137273222/7b22a977-338d-4345-b262-6c12ce3baabb">
also this is what I get from jwt.ms, I suspect, there is no permission to do anything!
<img width="359" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-python/assets/137273222/fede6f43-c240-4641-8fbe-6145b6acc0e1">

**Comment by tikicoder** [comment]
@ThomasUN000000000 
More than likely you are correct. My point is for the Ms side. That this python sdk is about interacting with the Ms graph, so if you don't have access to any subs that is ok. It's not needed and shouldn't be expected or required. As none of the stuff your interacting with has to be azure related.

Fortunately, for me I have a semi working wrapper I am fixing up. This sdk does not even seem in a state to use in dev projects.

**Comment by ThomasUN000000000** [comment]
> @ThomasUN000000000 More than likely you are correct. My point is for the Ms side. That this python sdk is about interacting with the Ms graph, so if you don't have access to any subs that is ok. It's not needed and shouldn't be expected or required. As none of the stuff your interacting with has to be azure related.
> 
> Fortunately, for me I have a semi working wrapper I am fixing up. This sdk does not even seem in a state to use in dev projects.

Mate, do you have any idea on how to make scopes to be like this format?
`scopes = ["IMAP.AccessAsUser.All", "Mail.Read", "Mail.Read.Shared", "Mail.ReadBasic","Mail.ReadWrite","Mail.ReadWrite.Shared"]`
in the graph training example, I can do it
[https://github.com/microsoftgraph/microsoft-graph-training](url)

**Comment by tikicoder** [comment]
@ThomasUN000000000 
You can't unless you do a custom auth class. I have looked into the cli credential class and the issue is it connects with the cli and only used the --reaource-type and there is no option for --scope. I would presume the others are similar.

**Comment by samwelkanda** [comment]
Apologies for the above. As you correctly deduced, this was caused by differences between the README samples and the publicly available SDK version. Please update to `v1.0.0a13`. 

@tikicoder  I suspect the deserialization issues were caused by similar updates to the `json-serialization` library that were ahead of the available SDK version. Please confirm if you are still facing the issue after updating.

@ThomasUN000000000 the default base url of the SDK is set to `https://graph.microsoft.com/v1.0`. If you want to access the China cloud you can set the base url like so:

```py
credential = InteractiveBrowserCredential()
scopes = ['https://microsoftgraph.chinacloudapi.cn/.default']

auth_provider = AzureIdentityAuthenticationProvider(credential, scopes=scopes)

# Initialize a request adapter with the auth provider.
request_adapter = GraphRequestAdapter(auth_provider)

# Set the base url for the http requests
request_adapter.base_url = "https://microsoftgraph.chinacloudapi.cn"

# Create an API client with the request adapter.
client = GraphServiceClient(request_adapter=request_adapter)
```

I hope that helps.

**Comment by tikicoder** [comment]
@samwelkanda thanks for that update.

I have switched back to my basic wrapper. I am working on something that I was to have more stable, maybe not quite production yet but at least a good beta. I am also doing more around workbooks and I don't think the support is there for it yet.
