### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by danielniccoli** [microsoftgraph/msgraph-sdk-python#282]
I'm looking for the documentation or a reference for this package. The docs folder contains only some samples. Generally, a complete reference of all classes and methods helps (me) to get a quick overview of what the SDK has to offer. Is there any?

**Comment by andyhird** [comment]
I'd like to second this request - once you get past the basic samples on the 365 Graph API site there's no documentation obviously available (the pypi doc page link is a 404 for example) for the SDK.
For example - within a few hours of trying to use the SDK I've hit basic questions like how to call APIs when you're using application authentication as opposed to using delegated user auth - i.e. you can't use /me. So if I'm trying to use the send mail API in this form - POST /users/{id | userPrincipalName}/sendMail - there's no examples for the python SDK.

Or if I'm calling get_users and getting a UserCollectionResponse object back - there's no documentation I can find of what methods or properties are available on the response objects. 

Thanks!

**Comment by danielniccoli** [comment]
@samwelkanda Can you help with this? At the moment, this SDK is not usable and every little thing requires extensive search through a (horribly auto-generated) code base and internet. That's not what I call an SDK, but rather a big box of assorted LEGO's dumped on the floor.

**Comment by samwelkanda** [comment]
Hi @danielniccoli @andyhird 

Due to the size of the Microsoft Graph API and the number of SDKs we support, our approach to documentation is very streamlined and centered around the Microsoft Graph Docs Portal. This is ensure the experience is consistent across the languages.

`Introduction`: https://learn.microsoft.com/en-us/graph/overview?view=graph-rest-1.0
`Authentication`: https://learn.microsoft.com/en-us/graph/tutorials?view=graph-rest-1.0
`SDKS`: https://learn.microsoft.com/en-us/graph/sdks/sdk-installation?view=graph-rest-1.0
`Customizing responses`: https://learn.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=python
`API Reference`: https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

For language specific snippets, always navigate to the Python tab in the docs
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/40166690/3c3cdd00-748a-490f-a565-0851ecb432fc)




We have the Graph Docs

**Comment by samwelkanda** [comment]
We also have the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to try out requests, discover/modify permissions and get sdk code snippets equivalent to the http request
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/40166690/b936239f-a34b-4f1e-8e80-d9e8c38ca93e)

**Comment by danielniccoli** [comment]
@samwelkanda 

These are useless. The question was not how to use the Graph API.
> Introduction: https://learn.microsoft.com/en-us/graph/overview?view=graph-rest-1.0
> Authentication: https://learn.microsoft.com/en-us/graph/tutorials?view=graph-rest-1.0
> SDKS: https://learn.microsoft.com/en-us/graph/sdks/sdk-installation?view=graph-rest-1.0

These come close, but they still lack proper SDK documentation:

> Customizing responses: https://learn.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=python
> API Reference: https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

Don't get me wrong, that helped, but they're still very specific examples. They also lack import statements. Since Pylance is somehow unable to get insight into the SDK, intellisense doesn't work and without it being documented anywhere, I had to search through the code to find from where I had to import e.g., `UsersRequestBuilderGetQueryParameters`. Overall, knowing that the SDK is being developed by Microsoft, it surprises me how many flaws there are with the SDK and the documentation overall.

**Comment by WardenHub** [comment]
I tried to get this to work this afternoon,  the examples from https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=python#example-2-create-a-message-with-custom-internet-message-headers-and-send-the-message are unusable.

On top of that the MIME content parser cant handle html without throwing an error, all the while microsoft enforces usage of this system with the [Deprecation of Basic authentication in Exchange Online | Microsoft Learn](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online)

**Comment by KonTheCat** [comment]
Very much seconding the general idea here. I am struggling to figure out how to do something as basic as uploading a file to a SharePoint site with this SDK. And I did try the Graph explorer, maybe something is not clicking. This SDK is great because it supports the Azure authentication libraries that we want to use but the lack of documentation is making this difficult.
