### ISSUE TITLE
Error: The 'filter' query option must be provided.

### ISSUE THREAD

**Issue by stvpwrs** [microsoftgraph/msgraph-sdk-python#365]
Hello,

I'm sure some of the issues I'm seeing are a lack of understanding how this library works. I'm trying to understand the patterns that have to be in place, but when I run the following code I get this odd error that the `Error: The 'filter' query option must be provided.` and I don't understand why I have to pass a filter.

```
items = await client.drives.by_drive_id(drive.id).items.get()
```

If I do pass a filter in I then get `Error: Expand cannot be null or empty.`. I'm a bit at a loss of what's going on here.

**Comment by justmike1** [comment]
hey, did you solve it? I am having the same issue

**Comment by glinft** [comment]
Did you solve it?
I am having the same issue today.

**Comment by stvpwrs** [comment]
No luck @justmike1 and @glinft. I don't think that code is actually valid, but it did appear in some samples at one point.

**Comment by andrueastman** [comment]
Thanks for raising this @stvpwrs 

The drive api does not support listing items from the `items` segment. 

Any chance the documentation below is helpful?
https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http

**Comment by kristianandre** [comment]
I find it very strange that several users, me included, have copied [one](https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/docs/drives_samples.md#1-list-all-drives-get-drives) of the few code samples in this repo, and it doesn't work. My conclusion so far is that it's a lot more clunky and hard to work with the Python SDK instead of doing requests directly to the Graph API. How can one find files by relative path for example? It seems like one needs to acquire the ids of every drive, site and item one wants to request, but that gets challenging when the code samples to get those ids don't work.

@andrueastman In the link you sent under [this](https://github.com/storebrand-technology/stb-prod-data-platform) section, the HTTP tab correctly shows how to list files in the root of a drive. However, the Python tab is identical to the one in section "List children of a DriveItem with a known ID" that requires one to get a DriveItem id first. While there is no Python version for "known path".

More working code samples would be greatly appreciated.

**Comment by venukalam** [comment]
This example in the docs is still outdated. It’s confusing and wasting a ton of people’s time.

**Comment by pierremonico** [comment]
Even better on my end: I get the same error, but when I pass in the `$filter` query param, although it now works, the queries actually have no effect, all items are returned.

**Comment by alesposto** [comment]
@pierremonico did you fix it? Can you explain what did you change? Ty

**Comment by ThongLai** [comment]
I believe you follow this sample here: (3. LIST ALL THE ITEMS IN A DRIVE [GET /drives/{id}/items](https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/docs/drives_samples.md)

**Comment by ThongLai** [comment]
I believe you followed the sample provided here: https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/docs/drives_samples.md. 

Specifically, the method `client.drives.by_drive_id('DRIVE_ID').items.get()` in section **3. LIST ALL THE ITEMS IN A DRIVE** is not working. 
So instead, you can use the method from section **6. GET ITEMS IN THE ROOT FOLDER OF THE DRIVE**: `client.drives.by_drive_id('DRIVE_ID').items.by_drive_item_id('root').children.get()`

**Differences Between Methods**
As I could not test on `.items.get()`. However, I believe: 
- `.items.get()` returns a FLAT LIST of ALL files and folders
- `.items.by_drive_item_id('root').children.get()` returns only the children of the root folder.

For example, with this structure:
```
Root/
  ├── File1.txt
  ├── Folder1/
  │   └── File2.txt
  └── File3.txt
```
- Using `.items.get()` (will produce an error), I assume it is intended to return: `File1.txt`, `Folder1`, `File2.txt`, `File3.txt`
- Using `.items.by_drive_item_id('root').children.get()`, it would return only: `File1.txt`, `Folder1`, `File3.txt` 
(As `File2.txt` is in `Folder1` not `root`)

If you still want to get a flat list of all drive items, you can use `.items.by_drive_item_id('root').children.get()` and then loop through all the found folders.

At least for now, this is the only solution I have come up with. Please let me know if there's a fix for this!
