### ISSUE TITLE
version msgraph-sdk==1.0.0a12 have been update and give TypeError: 'HeadersCollection' object does not support item assignment

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/msgraph-sdk-python#432]
Context: We build an api to sync data to azure, running in a container.
Since we rebuild the container this error appear, after digging, the file `venv/lib/python3.11/site-packages/kiota_abstractions/request_information.py` is not the same in version 1.0.0a12
md5sum of the old one: 3a1b7ee35931c5c9cc1c45912b2665c8
md5sum of the new one: 4825326de8f5a213f36cd95cfea30a4b

full diff attached.
[diff.patch](https://github.com/microsoftgraph/msgraph-sdk-python/files/13178233/diff.patch)

Can you rollback this, or propose a fix for that please ?

**Comment by samwelkanda** [comment]
Hi @EFG-TheDevopsGuy 

Thanks for creating this issue.  The above changes were done to align header management across all our supported languages. As of `microsoft-kiota-abstractions >=0.9.0` we use a `HeadersCollection` class to manage our headers instead of a python dictionary.

Here's an example to set request headers with the current setup:
```py
  query_params = MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters(
      select=['subject',], skip=1, top=5
  )
  request_config = MessagesRequestBuilder.MessagesRequestBuilderGetRequestConfiguration(
      query_parameters=query_params,
  )
request_config.headers.add("prefer", "outlook.body-content-type-text")
```

I would highly advice you to upgrade to the latest `rc` version as this was the last breaking change heading to a GA version.
