### ISSUE TITLE
It takes 3 minutes to import modules from msgraph

### ISSUE THREAD

**Issue by mingchun-zhao** [microsoftgraph/msgraph-sdk-python#50]
Hi, 
It looks like importing modules from `msgraph` takes more than 3 minutes.

```python
import time
start = time.time()
from msgraph import GraphRequestAdapter, GraphServiceClient
print(time.time() - start)
```

```python
217.1570749282837
```

Could you give me some advice?
Thanks.

**Comment by peombwa** [comment]
@mingchun-zhao, you've opened the issue in the wrong repository, Microsoft Graph PowerShell. I'll transfer the issue to [msgraph-sdk-python](https://github.com/microsoftgraph/msgraph-sdk-python) repro.

**Comment by mingchun-zhao** [comment]
@peombwa , Thanks!

**Comment by samwelkanda** [comment]
Hi, @mingchun-zhao. 

Thanks for trying out the preview SDK and for creating this issue. This was a known issue with earlier versions of the SDK(<v1.0.0a4) and was subsequently fixed by implementing lazy module imports. Please update to the latest version of the package and let us know if you are still facing the same challenge.

**Comment by mingchun-zhao** [comment]
Hi, @samwelkanda

Thank you for your answer.
I was able to confirm that the problem does not occur in the latest version.
thanks  again.
