### ISSUE TITLE
Missing Function in Python SDK - PlannerAssignment

### ISSUE THREAD

**Issue by murphyb12** [microsoftgraph/msgraph-sdk-python#636]
The Python SDK uses multiple models for creating and assigning tasks in the Planner, however the model PlannerAssignment is missing in the folder msgraph > generated >models > planner_assignment. 

This function works in the Msgraph Explorer

**Comment by shemogumbe** [comment]
Hello @murphyb12 thanks for using the SDK and for raising this

Could you knildy provide more context to help us reproduce this.

These could include:

- The snippet you are running
- the documentation  from which your code is based
- The error message you find

**Comment by ph-eip** [comment]
This issue was also raised over at the Java SDK repo.: https://github.com/microsoftgraph/msgraph-sdk-java/issues/1873

Basically there is no module for PlannerAssignment across all languages:

`ModuleNotFoundError: No module named 'msgraph.generated.models.planner_assignment'`

...despite it being shown in the docs as available:

![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/85677784/a88458a1-b740-41fd-936d-bee2cb22eb5d)
https://learn.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=python
