### ISSUE TITLE
to_post_request_information() raises error when omitting an optional parameter

### ISSUE THREAD

**Issue by danielniccoli** [microsoftgraph/msgraph-sdk-python#665]
This is just one of many classes where `to_post_request_information()` is implemented. It takes an optional parameter but then checks if it is None and raises and error if it is.

https://github.com/microsoftgraph/msgraph-sdk-python/blob/fe603589482e1043031317623b2d3ce3950ec104/msgraph/generated/users/item/send_mail/send_mail_request_builder.py#L51-L64

**Comment by shemogumbe** [comment]
Hello,
Thanks for using the SDK and for raising this.
We have since resolved this in our generation https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/msgraph/generated/users/item/send_mail/send_mail_request_builder.py in a closed task [here](https://github.com/microsoft/kiota/issues/4507)
